# Generated by Django 5.0 on 2023-12-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialApp',
        ),
    ]
